### ISSUE TITLE
Fully static build ?

### ISSUE THREAD

**Issue by Booklordofthedings** [kochol/CurlBeef#2]
I want to build the program statically. but even with the only listed dependency being the libcurl.lib file it will error if it cant find the dll's.
Any idea why that is and how I could fix it ?

**Comment by kochol** [comment]
I get the compiled files from https://vcpkg.io you can get static files with this command and replace them in dist folder
`.\vcpkg install curl:x64-windows-static zlib:x64-windows-static`

**Comment by Booklordofthedings** [comment]
Yup that works.
For anyone else attempting to do so:
You still need to add
`Ws2_32.Lib Wldap32.Lib Crypt32.Lib advapi32.lib`
as "other linker flags" in the curl project preferences in the beef ide.
